# -*- mode: ruby -*-
# vi: set ft=ruby :

PRIVATE_IP="10.10.10.4"

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: PRIVATE_IP # private IP for docker
end
