# -*- mode: ruby -*-
# vi: set ft=ruby :

PORT_WEB = 8088
PORT_DB  = 5123
APP_HOME = "/usr/src/app"
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: PORT_WEB, host: PORT_WEB
  config.vm.network "forwarded_port", guest: PORT_DB, host: PORT_DB
  config.vm.synced_folder ".", "#{APP_HOME}", type: "rsync",
    rsync__exclude: [".git/", "node_modules"]

  #config.vm.provision "shell", path: "provision.sh"
end
