# -*- mode: ruby -*-
# vi: set ft=ruby :

PORT = 8080

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: PORT, host: PORT
  config.vm.provision "docker" do |docker|
    docker.build_image "/vagrant", args: "-t web"
    docker.run "web" , args: "-p #{PORT}:#{PORT}" # container
  end
end
